#!/usr/bin/env python3
"""
Site Manager (GUI)
- Backend & frontend management for a static site
- Tabs: Content, Search Index, Preview, Deploy
- Self-contained: tkinter + stdlib only

Run: python tools/site_manager/site_manager.py
"""
import os
import sys
import json
import threading
import webbrowser
import subprocess
from pathlib import Path
from http.server import ThreadingHTTPServer, SimpleHTTPRequestHandler
import tkinter as tk
from tkinter import ttk, messagebox

# -----------------------------------------------------------------------------
# CONFIG & PATHS
# This section sets up project root and common directories.
# -----------------------------------------------------------------------------
ROOT = Path(__file__).resolve().parents[2]
PROJECTS = ROOT / 'projects'
TOOLS = ROOT / 'tools'

# -----------------------------------------------------------------------------
# HELPERS
# This section contains filesystem utilities and report writers.
# -----------------------------------------------------------------------------

def safe_write(path: Path, content: str):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding='utf-8')


def list_html_files():
    skip = {'.venv', 'venv', 'node_modules', '.git', 'tools'}
    files = []
    for p in ROOT.rglob('*.html'):
        if any(part in skip for part in p.relative_to(ROOT).parts):
            continue
        files.append(p)
    return files

# -----------------------------------------------------------------------------
# TEMPLATES
# This section defines minimal HTML templates for new content.
# -----------------------------------------------------------------------------
BASE_TEMPLATE = """<!DOCTYPE html>
<html lang=\"en\">
<head>
  <meta charset=\"UTF-8\">
  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">
  <title>{title}</title>
  <link rel=\"stylesheet\" href=\"{prefix}assets/css/universal-search.css\">
  <script src=\"{prefix}assets/js/theme-manager.js\"></script>
  <script src=\"{prefix}assets/js/universal-search.js\" defer></script>
  <style>body{font-family:Segoe UI,Roboto,Arial,sans-serif;padding:20px;}</style>
</head>
<body>
  <header>
    <h1>{title}</h1>
    <p>Generated by Site Manager</p>
    <hr>
  </header>
  <main>
    <section>
      <h2>Section Title</h2>
      <p>Edit this content in your editor.</p>
    </section>
  </main>
</body>
</html>
"""

# Additional templates for user-friendly scaffolding
PAGE_LANDING_TEMPLATE = """<!DOCTYPE html>
<html lang=\"en\">
<head>
    <meta charset=\"UTF-8\">
    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">
    <title>{title}</title>
    <link rel=\"stylesheet\" href=\"{prefix}assets/css/universal-search.css\">
    <script src=\"{prefix}assets/js/theme-manager.js\"></script>
    <script src=\"{prefix}assets/js/universal-search.js\" defer></script>
    <style>
        :root{--bg:#0b1b2b;--fg:#eaf2fb;--accent:#4fb0ff}
        body{margin:0;font-family:Segoe UI,Roboto,Arial,sans-serif;background:var(--bg);color:var(--fg)}
        .hero{padding:80px 24px;text-align:center}
        .hero h1{font-size:40px;margin:0 0 12px}
        .hero p{font-size:18px;opacity:.9}
        .cta{margin-top:20px}
        .cta a{display:inline-block;padding:12px 18px;background:var(--accent);color:#001b2b;text-decoration:none;border-radius:6px}
        main{background:#fff;color:#222;border-radius:12px;margin:24px;padding:24px}
    </style>
    </head>
<body>
    <div class=\"hero\">
        <h1>{title}</h1>
        <p>A friendly landing page with a clear call to action.</p>
        <div class=\"cta\"><a href=\"#get-started\">Get Started</a></div>
    </div>
    <main>
        <h2 id=\"get-started\">Next steps</h2>
        <p>Replace this content with your own sections, images, and links.</p>
    </main>
</body>
</html>
"""

PROJECT_APP_INDEX = """<!DOCTYPE html>
<html lang=\"en\">
<head>
    <meta charset=\"UTF-8\">
    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">
    <title>{title}</title>
    <link rel=\"stylesheet\" href=\"styles.css\">
    <link rel=\"stylesheet\" href=\"{prefix}assets/css/universal-search.css\">
    <script src=\"{prefix}assets/js/theme-manager.js\"></script>
    <script src=\"{prefix}assets/js/universal-search.js\" defer></script>
</head>
<body>
    <header>
        <h1>{title}</h1>
        <p>Project starter with JS + CSS files you can edit.</p>
        <hr>
    </header>
    <main>
        <section>
            <h2>Welcome</h2>
            <p>Your app JavaScript lives in <strong>main.js</strong>. Styles live in <strong>styles.css</strong>.</p>
        </section>
    </main>
    <script src=\"main.js\"></script>
</body>
</html>
"""

PROJECT_APP_MAIN_JS = """// App Starter
document.addEventListener('DOMContentLoaded', () => {
    console.log('App ready');
    const el = document.createElement('div');
    el.textContent = 'Edit main.js to build your app.';
    document.body.appendChild(el);
});
"""

PROJECT_APP_STYLES_CSS = """/* Styles for App Starter */
body{font-family:Segoe UI,Roboto,Arial,sans-serif;padding:20px}
h1{margin:0 0 8px}
"""

PROJECT_GAME_INDEX = """<!DOCTYPE html>
<html lang=\"en\">
<head>
    <meta charset=\"UTF-8\">
    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">
    <title>{title}</title>
    <link rel=\"stylesheet\" href=\"styles.css\">
    <link rel=\"stylesheet\" href=\"{prefix}assets/css/universal-search.css\">
    <script src=\"{prefix}assets/js/theme-manager.js\"></script>
    <script src=\"{prefix}assets/js/universal-search.js\" defer></script>
</head>
<body>
    <header>
        <h1>{title}</h1>
        <p>Game starter with a canvas and a simple update loop.</p>
        <hr>
    </header>
    <canvas id=\"game\" width=\"640\" height=\"360\" style=\"border:1px solid #999\"></canvas>
    <script src=\"main.js\"></script>
</body>
</html>
"""

PROJECT_GAME_MAIN_JS = """// Game Starter
const canvas = document.getElementById('game');
const ctx = canvas.getContext('2d');
let t = 0;
function loop(){
    t+=0.02;
    ctx.fillStyle = '#121212';
    ctx.fillRect(0,0,canvas.width,canvas.height);
    ctx.fillStyle = '#4fb0ff';
    ctx.beginPath();
    ctx.arc(320+Math.sin(t)*120, 180, 24, 0, Math.PI*2);
    ctx.fill();
    requestAnimationFrame(loop);
}
loop();
"""

PROJECT_GAME_STYLES_CSS = """/* Styles for Game Starter */
body{font-family:Segoe UI,Roboto,Arial,sans-serif;padding:20px}
canvas{display:block;margin-top:12px}
"""

PROJECT_FORM_INDEX = """<!DOCTYPE html>
<html lang=\"en\">
<head>
    <meta charset=\"UTF-8\">
    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">
    <title>{title}</title>
    <link rel=\"stylesheet\" href=\"styles.css\">
    <link rel=\"stylesheet\" href=\"{prefix}assets/css/universal-search.css\">
    <script src=\"{prefix}assets/js/theme-manager.js\"></script>
    <script src=\"{prefix}assets/js/universal-search.js\" defer></script>
</head>
<body>
    <header>
        <h1>{title}</h1>
        <p>Form tool starter with a simple submit handler.</p>
        <hr>
    </header>
    <main>
        <form id=\"tool-form\">
            <label>Value <input name=\"value\" required></label>
            <button type=\"submit\">Run</button>
        </form>
        <pre id=\"out\"></pre>
    </main>
    <script src=\"main.js\"></script>
</body>
</html>
"""

PROJECT_FORM_MAIN_JS = """// Form Tool Starter
document.getElementById('tool-form').addEventListener('submit', (e) => {
    e.preventDefault();
    const val = new FormData(e.target).get('value');
    document.getElementById('out').textContent = `You entered: ${val}`;
});
"""

PROJECT_FORM_STYLES_CSS = """/* Styles for Form Tool */
body{font-family:Segoe UI,Roboto,Arial,sans-serif;padding:20px}
label{display:block;margin:8px 0}
pre{background:#f5f5f5;border:1px solid #ddd;padding:12px;border-radius:8px}
"""

# -----------------------------------------------------------------------------
# SEARCH INDEX
# This section builds a simple search index (titles + headings) for front-end.
# -----------------------------------------------------------------------------

def build_search_index():
    import re
    title_re = re.compile(r"<title>(.*?)</title>", re.IGNORECASE|re.DOTALL)
    h_re = re.compile(r"<(h[1-3])[^>]*>(.*?)</\1>", re.IGNORECASE|re.DOTALL)

    items = []
    for f in list_html_files():
        rel = f.relative_to(ROOT).as_posix()
        text = f.read_text(encoding='utf-8', errors='ignore')
        title_m = title_re.search(text)
        title = (title_m.group(1).strip() if title_m else rel)
        headings = [m.group(2).strip() for m in h_re.finditer(text)]
        items.append({
            'path': rel,
            'title': title,
            'headings': headings[:20],
        })

    out = TOOLS / 'site_manager' / 'search-index.json'
    safe_write(out, json.dumps({'items': items}, indent=2))
    return out

# -----------------------------------------------------------------------------
# PREVIEW SERVER
# This section starts a local HTTP server in a background thread.
# -----------------------------------------------------------------------------
class RootHandler(SimpleHTTPRequestHandler):
    def translate_path(self, path):
        # Serve from site ROOT instead of current working directory
        full = (ROOT / path.lstrip('/')).resolve()
        return str(full)

_server = None
_server_thread = None


def start_server(port=8000):
    global _server, _server_thread
    if _server:
        return True
    _server = ThreadingHTTPServer(('127.0.0.1', port), RootHandler)
    _server_thread = threading.Thread(target=_server.serve_forever, daemon=True)
    _server_thread.start()
    return True


def stop_server():
    global _server
    if _server:
        try:
            _server.shutdown()
        except Exception:
            pass
        _server = None
    return True

# -----------------------------------------------------------------------------
# DEPLOY (GIT)
# This section runs git commands to commit and push changes.
# -----------------------------------------------------------------------------

def run_git(args):
    return subprocess.run(['git'] + args, cwd=str(ROOT), capture_output=True, text=True)

# -----------------------------------------------------------------------------
# GUI
# This section defines the Tkinter application with tabs and actions.
# -----------------------------------------------------------------------------
class SiteManagerApp(tk.Tk):
    def __init__(self):
        super().__init__()
        self.title('Site Manager')
        self.geometry('960x640')
        self.minsize(860, 540)
        self.create_widgets()

    def create_widgets(self):
        nb = ttk.Notebook(self)
        nb.pack(fill='both', expand=True)

        self.content_tab = self._build_content_tab(nb)
        self.search_tab = self._build_search_tab(nb)
        self.preview_tab = self._build_preview_tab(nb)
        self.deploy_tab = self._build_deploy_tab(nb)

    # ---------------------- Content Tab ----------------------
    # // this section does content creation and scaffolding
    def _build_content_tab(self, nb):
        frame = ttk.Frame(nb)
        nb.add(frame, text='Content')

        ttk.Label(frame, text='Create New Page / Project', font=('Segoe UI', 12, 'bold')).pack(anchor='w', padx=12, pady=(12, 6))
        ttk.Label(frame, text='Pick a template, name it, and see exactly where files will be created. No coding needed.', wraplength=820).pack(anchor='w', padx=12, pady=(0, 6))

        form = ttk.Frame(frame)
        form.pack(fill='x', padx=12)

        ttk.Label(form, text='Type').grid(row=0, column=0, sticky='w')
        self.kind_var = tk.StringVar(value='project')
        ttk.Combobox(form, textvariable=self.kind_var, values=['project', 'page'], width=12).grid(row=0, column=1, sticky='w')

        ttk.Label(form, text='Template').grid(row=0, column=2, sticky='w', padx=(20,0))
        self.template_var = tk.StringVar()
        self.template_combo = ttk.Combobox(form, textvariable=self.template_var, values=[], width=22)
        self.template_combo.grid(row=0, column=3, sticky='w')

        ttk.Label(form, text='Name').grid(row=1, column=0, sticky='w')
        self.name_var = tk.StringVar()
        ttk.Entry(form, textvariable=self.name_var, width=28).grid(row=1, column=1, sticky='w')

        ttk.Label(form, text='Title').grid(row=2, column=0, sticky='w')
        self.title_var = tk.StringVar()
        ttk.Entry(form, textvariable=self.title_var, width=28).grid(row=2, column=1, sticky='w')

        # Template description box
        desc_frame = ttk.LabelFrame(frame, text='Template Description')
        desc_frame.pack(fill='x', padx=12, pady=(10, 6))
        self.template_desc = tk.Text(desc_frame, height=4, wrap='word', font=('Segoe UI', 10))
        self.template_desc.pack(fill='x', padx=8, pady=8)
        self.template_desc.configure(state='disabled')

        # Route + files preview
        preview_frame = ttk.LabelFrame(frame, text='Where files will be created')
        preview_frame.pack(fill='both', expand=True, padx=12, pady=(6, 8))
        self.preview_box = tk.Text(preview_frame, height=10, wrap='word', font=('Consolas', 10))
        self.preview_box.pack(fill='both', expand=True, padx=8, pady=8)
        self.preview_box.insert('end', 'Select Type, Template, and Name to see the exact folder and files that will be created.\n')

        btns = ttk.Frame(frame)
        btns.pack(fill='x', padx=12, pady=8)
        ttk.Button(btns, text='Create', command=self.create_content).pack(side='left')
        ttk.Button(btns, text='Open Target Folder', command=self.open_target_folder).pack(side='left', padx=6)

        self.content_log = tk.Text(frame, height=8, wrap='word', font=('Consolas', 10))
        self.content_log.pack(fill='both', expand=True, padx=12, pady=(6, 12))
        self.content_log.insert('end', 'Ready. This tool will create files for you and show exactly where they go.\n')

        # Bind changes to update templates and preview
        self.kind_var.trace_add('write', lambda *_: self._refresh_templates())
        self.template_var.trace_add('write', lambda *_: self.update_preview())
        self.name_var.trace_add('write', lambda *_: self.update_preview())
        self.title_var.trace_add('write', lambda *_: self.update_preview())
        self._refresh_templates()
        return frame

    def create_content(self):
        kind = self.kind_var.get().strip()
        name = self.name_var.get().strip()
        title = self.title_var.get().strip() or name or 'New Page'
        if not name:
            messagebox.showerror('Error', 'Name is required')
            return
        if any(c in name for c in ' \\/:*?"<>|'):
            messagebox.showerror('Error', 'Name contains invalid characters')
            return

        if kind == 'project':
            base = PROJECTS / name
            prefix = '../../'
        else:
            base = ROOT / name
            # Pages live at /<name>/, assets live at /assets/... → use '../'
            prefix = '../'

        # Render selected template
        tpl_id = self.template_var.get().strip() or ('app-starter' if kind == 'project' else 'basic-page')
        files_map = self._render_template_files(kind, tpl_id, title, prefix)

        base.mkdir(parents=True, exist_ok=True)
        created = []
        skipped = []
        for rel, content in files_map.items():
            path = base / rel
            if path.exists():
                skipped.append(path.relative_to(ROOT).as_posix())
                continue
            safe_write(path, content)
            created.append(path.relative_to(ROOT).as_posix())

        if created:
            self.content_log.insert('end', 'Created files:\n' + '\n'.join(f'- {p}' for p in created) + '\n')
        if skipped:
            self.content_log.insert('end', 'Skipped (already exist):\n' + '\n'.join(f'- {p}' for p in skipped) + '\n')
        self.content_log.see('end')
        # Refresh preview after creation
        self.update_preview()

    def open_target_folder(self):
        kind = self.kind_var.get().strip()
        name = self.name_var.get().strip()
        if not name:
            messagebox.showinfo('Info', 'Enter a Name first.')
            return
        base = (PROJECTS / name) if kind == 'project' else (ROOT / name)
        base.mkdir(parents=True, exist_ok=True)
        try:
            if os.name == 'nt':
                os.startfile(str(base))
            elif sys.platform == 'darwin':
                subprocess.run(['open', str(base)])
            else:
                subprocess.run(['xdg-open', str(base)])
        except Exception as e:
            messagebox.showerror('Error', f'Could not open folder:\n{e}')

    def _refresh_templates(self):
        kind = self.kind_var.get().strip()
        # Available templates by kind
        if kind == 'project':
            options = ['app-starter', 'game-starter', 'form-tool']
        else:
            options = ['basic-page', 'landing-page']
        self.template_combo['values'] = options
        # Set default
        self.template_var.set(options[0])
        self.update_preview()

    def update_preview(self):
        kind = self.kind_var.get().strip()
        name = (self.name_var.get().strip() or '<your-name>')
        title = (self.title_var.get().strip() or name)
        tpl_id = self.template_var.get().strip()

        if kind == 'project':
            base = PROJECTS / name
            prefix = '../../'
            route = f'projects/{name}/'
            url = f'http://127.0.0.1:8000/{route}'
        else:
            base = ROOT / name
            # Pages live at /<name>/, assets live at /assets/... → use '../'
            prefix = '../'
            route = f'{name}/'
            url = f'http://127.0.0.1:8000/{route}'

        files_map = self._render_template_files(kind, tpl_id, title, prefix)
        files_list = '\n'.join(f'- {route}{rel}' for rel in files_map.keys())

        # Update description text
        desc = self._template_description(kind, tpl_id)
        self.template_desc.configure(state='normal')
        self.template_desc.delete('1.0', 'end')
        self.template_desc.insert('end', desc)
        self.template_desc.configure(state='disabled')

        # Update preview text
        self.preview_box.delete('1.0', 'end')
        self.preview_box.insert('end', f'Target Folder: {base.relative_to(ROOT).as_posix()}/\n')
        self.preview_box.insert('end', f'Preview URL: {url}\n')
        self.preview_box.insert('end', '\nFiles that will be created:\n')
        self.preview_box.insert('end', files_list + '\n')
        self.preview_box.insert('end', '\nNotes:\n- Includes theme + universal search scripts automatically.\n- You can edit titles and content later in your editor.\n')

    # ---------------------- Template Renderers ----------------------
    def _template_description(self, kind: str, tpl_id: str) -> str:
        descriptions = {
            ('page', 'basic-page'): 'Simple content page. Good for notes, sections, and general info. Comes with site theme + search links.',
            ('page', 'landing-page'): 'Hero landing page. Big title, call-to-action, and a clean main section you can expand.',
            ('project', 'app-starter'): 'App starter (index.html + main.js + styles.css). Edit JS/CSS to build your app.',
            ('project', 'game-starter'): 'Game starter (index.html + canvas + main.js). A minimal draw loop to start experimenting.',
            ('project', 'form-tool'): 'Form tool starter (index.html + main.js + styles.css). Basic input → output example.',
        }
        return descriptions.get((kind, tpl_id), 'Template description')

    def _render_template_files(self, kind: str, tpl_id: str, title: str, prefix: str):
        # Returns { relative_path: file_contents }
        if kind == 'page':
            if tpl_id == 'landing-page':
                return {
                    'index.html': PAGE_LANDING_TEMPLATE.format(title=title, prefix=prefix)
                }
            # default
            return {'index.html': BASE_TEMPLATE.format(title=title, prefix=prefix)}

        # kind == 'project'
        if tpl_id == 'game-starter':
            return {
                'index.html': PROJECT_GAME_INDEX.format(title=title, prefix=prefix),
                'main.js': PROJECT_GAME_MAIN_JS,
                'styles.css': PROJECT_GAME_STYLES_CSS,
                'README.txt': 'Edit main.js and styles.css. Open index.html in a browser to preview your game.'
            }
        if tpl_id == 'form-tool':
            return {
                'index.html': PROJECT_FORM_INDEX.format(title=title, prefix=prefix),
                'main.js': PROJECT_FORM_MAIN_JS,
                'styles.css': PROJECT_FORM_STYLES_CSS,
                'README.txt': 'Form tool starter. Update the form and JS to process inputs.'
            }
        # default app-starter
        return {
            'index.html': PROJECT_APP_INDEX.format(title=title, prefix=prefix),
            'main.js': PROJECT_APP_MAIN_JS,
            'styles.css': PROJECT_APP_STYLES_CSS,
            'README.txt': 'App starter. Edit main.js and styles.css to build your feature.'
        }

    # -------------------- Search Index Tab -------------------
    # // this section builds a simple index used by front-end search
    def _build_search_tab(self, nb):
        frame = ttk.Frame(nb)
        nb.add(frame, text='Search Index')
        ttk.Label(frame, text='Build front-end search index (titles + headings)', font=('Segoe UI', 12, 'bold')).pack(anchor='w', padx=12, pady=(12, 6))
        ttk.Button(frame, text='Build Index', command=self.on_build_index).pack(anchor='w', padx=12)

        self.search_log = tk.Text(frame, height=18, wrap='word', font=('Consolas', 10))
        self.search_log.pack(fill='both', expand=True, padx=12, pady=(6, 12))
        self.search_log.insert('end', 'Click Build Index to generate tools/site_manager/search-index.json\n')
        return frame

    def on_build_index(self):
        out = build_search_index()
        self.search_log.insert('end', f'Wrote: {out.relative_to(ROOT)}\n')
        self.search_log.see('end')

    # ---------------------- Preview Tab ----------------------
    # // this section starts a local server and opens browser
    def _build_preview_tab(self, nb):
        frame = ttk.Frame(nb)
        nb.add(frame, text='Preview')
        ttk.Label(frame, text='Local Preview Server', font=('Segoe UI', 12, 'bold')).pack(anchor='w', padx=12, pady=(12, 6))

        btns = ttk.Frame(frame)
        btns.pack(anchor='w', padx=12)
        ttk.Button(btns, text='Start Server', command=self.on_start_server).pack(side='left')
        ttk.Button(btns, text='Open Home', command=self.on_open_home).pack(side='left', padx=6)
        ttk.Button(btns, text='Stop Server', command=self.on_stop_server).pack(side='left', padx=6)

        self.preview_log = tk.Text(frame, height=18, wrap='word', font=('Consolas', 10))
        self.preview_log.pack(fill='both', expand=True, padx=12, pady=(6, 12))
        self.preview_log.insert('end', 'Click Start Server to serve from project root on http://127.0.0.1:8000/\n')
        return frame

    def on_start_server(self):
        started = start_server(8000)
        self.preview_log.insert('end', 'Server started on http://127.0.0.1:8000/\n' if started else 'Server already running\n')
        self.preview_log.see('end')

    def on_open_home(self):
        webbrowser.open('http://127.0.0.1:8000/')

    def on_stop_server(self):
        stop_server()
        self.preview_log.insert('end', 'Server stopped\n')
        self.preview_log.see('end')

    # ----------------------- Deploy Tab ----------------------
    # // this section runs git commands to commit and push
    def _build_deploy_tab(self, nb):
        frame = ttk.Frame(nb)
        nb.add(frame, text='Deploy')
        ttk.Label(frame, text='GitHub Pages Deploy (finnworks.dev)', font=('Segoe UI', 12, 'bold')).pack(anchor='w', padx=12, pady=(12, 6))

        form = ttk.Frame(frame)
        form.pack(fill='x', padx=12)
        ttk.Label(form, text='Commit Message').grid(row=0, column=0, sticky='w')
        self.commit_var = tk.StringVar(value='Site Manager update')
        ttk.Entry(form, textvariable=self.commit_var, width=40).grid(row=0, column=1, sticky='w')

        btns = ttk.Frame(frame)
        btns.pack(anchor='w', padx=12, pady=8)
        ttk.Button(btns, text='Git Status', command=self.on_git_status).pack(side='left')
        ttk.Button(btns, text='Commit & Push', command=self.on_git_push).pack(side='left', padx=6)

        self.deploy_log = tk.Text(frame, height=18, wrap='word', font=('Consolas', 10))
        self.deploy_log.pack(fill='both', expand=True, padx=12, pady=(6, 12))
        self.deploy_log.insert('end', 'Ensure git is installed and remote is configured.\n')
        return frame

    def on_git_status(self):
        proc = run_git(['status'])
        self.deploy_log.insert('end', proc.stdout + (proc.stderr or ''))
        self.deploy_log.see('end')

    def on_git_push(self):
        msg = self.commit_var.get().strip() or 'Site Manager update'
        steps = [
            ['add', '-A'],
            ['commit', '-m', msg],
            ['push']
        ]
        for args in steps:
            proc = run_git(args)
            self.deploy_log.insert('end', f"$ git {' '.join(args)}\n" + proc.stdout + (proc.stderr or '') + '\n')
        self.deploy_log.see('end')

# -----------------------------------------------------------------------------
# ENTRY POINT
# -----------------------------------------------------------------------------
if __name__ == '__main__':
    app = SiteManagerApp()
    app.mainloop()
